name: 📤 Precheck + Export location_values

on:
  workflow_dispatch:

jobs:
  export-location-values:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
    steps:
      - name: 📥 Repository klonen
        uses: actions/checkout@v3

      - name: 🧰 Node installieren
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Abhängigkeiten installieren
        run: npm install

      - name: 🧪 Precheck location_values mit to_review-Flag
        run: node tools/precheck_location_values.js

      - name: 📤 Export location_values.json
        run: node tools/export_location_values.js

      - name: 💾 Commit exportierte Datei
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add public/data/location_values.json public/data/location_values_to_review.json || true
          git commit -m "🚥 Export location_values.json + Review Check" || echo "Nothing to commit"
          git push
