name: Run All Wind2Horizon Exports

on:
  workflow_dispatch:

jobs:
  export-locations-de:
    uses: ./.github/workflows/export_locations_de.yml

  export-locations-en:
    uses: ./.github/workflows/export_locations_en.yml

  export-locations-it:
    uses: ./.github/workflows/export_locations_it.yml

  export-locations-hr:
    uses: ./.github/workflows/export_locations_hr.yml

  export-locations-fr:
    uses: ./.github/workflows/export_locations_fr.yml

  export-categories:
    uses: ./.github/workflows/export_categories.yml

  export-location-values:
    uses: ./.github/workflows/export_location_values.yml
